
trigger:
  - master

pool:
  name: test
  agent: local1

#variables:
#/home/prashantp/Downloads/pipe/workingDir
steps:
- script: |
    npm install
    node --version
    npm run-script build
  workingDirectory: /home/prashantp/Downloads/pipe/workingDir/angularDemoProject
  displayName: 'npm install and build'


- script: |
    npm run-script start
  workingDirectory: /home/prashantp/Downloads/pipe/workingDir/angularDemoProject
  displayName: 'Host the application'