# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3.9"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    #ports:
    #  - "6900:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-beta-3-20210426
    container_name: selenium-hub
    environment:
      - GRID_BROWSER_TIMEOUT=240000
      - GRID_TIMEOUT=240000
    ports:
      - "4442:4442"
    #  - "4443:4443"
    #  - "4444:4444"
  
  testapp:
    container_name: testapp
    build: .
    #  context: .
    #  dockerfile: ./.docker/Dockerfile_dev
    image: prashanttestapp
    #volumes:
    #  - ./src:/app/src
    ports:               
      - "4200:4200"
    command: npm start

    depends_on:             
      - chrome
      - selenium-hub